kubernetes_version: "1.30.0"
container_runtime: "containerd"

kubeadm_token: "abcdef.0123456789abcdef"
kubernetes_pod_network_cidr: "192.168.0.0/16"
calico_version: "v3.26"

k8s_master_ip: "10.0.0.10"
k8s_control_plane_endpoint: "k8s-control.example.com"

# Метки для группировки нод
k8s_node_labels:
  - "role=worker"
  - "env=prod"

# Настройки cgroup для systemd (актуально для Ubuntu 22.04+)
kubelet_extra_args: "--cgroup-driver=systemd"
