---
# Дефолтные переменные для роли firewall (VyOS)

vyos_api_host: "fw.xsoft.local"       # адрес VyOS-контейнера/ВМ
vyos_api_port: 443                    # порт API (HTTPS)
vyos_api_user: "vyosadmin"            # пользователь для API
vyos_api_password: "Vy0sPassw0rd!"    # пароль (рекомендуется в Vault)

# Интерфейсы и сети
external_interface: "eth0"            # подключение к /22 (глобальная)
internal_interface: "eth1"            # подключение к /26 (инфра)
nat_outside: true                     # включить NAT на внешнем интерфейсе

# Список правил firewall (Order определяет приоритет)
firewall_rules:
  - name: "allow_ssh"
    action: "accept"
    protocol: "tcp"
    destination_port: 22
    description: "Allow SSH"
  - name: "allow_http"
    action: "accept"
    protocol: "tcp"
    destination_port: 80
    description: "Allow HTTP"
  - name: "allow_https"
    action: "accept"
    protocol: "tcp"
    destination_port: 443
    description: "Allow HTTPS"
  - name: "default_drop"
    action: "drop"
    protocol: "all"
    description: "Drop everything else"
