---
# Установка зависимостей системы
- name: Ensure required packages are installed
  apt:
    name:
      - curl
      - openssh-server
      - ca-certificates
      - tzdata
      - postfix       # для SMTP (можно проставить relayhost)
    state: present
    update_cache: yes
  become: true

# Добавление официального репозитория GitLab CE
- name: Add GitLab CE repository
  shell: |
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
  args:
    creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list
  become: true

# Установка пакета gitlab-ce
- name: Install gitlab-ce
  apt:
    name: gitlab-ce
    state: latest
    update_cache: yes
  become: true

# Генерация конфигурации /etc/gitlab/gitlab.rb
- name: Configure GitLab via template
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: '0644'
  vars:
    external_url: "{{ gitlab_external_url }}"
    ssh_port: "{{ gitlab_ssh_port }}"
    smtp_enable: "{{ gitlab_smtp_enable }}"
    smtp_address: "{{ gitlab_smtp_address }}"
    smtp_port: "{{ gitlab_smtp_port }}"
    smtp_user_name: "{{ gitlab_smtp_user_name }}"
    smtp_password: "{{ gitlab_smtp_password }}"
    smtp_domain: "{{ gitlab_smtp_domain }}"
    smtp_authentication: "{{ gitlab_smtp_authentication }}"
    smtp_starttls: "{{ gitlab_smtp_enable_starttls_auto }}"
  become: true

# Применение конфигурации
- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure
  args:
    creates: /var/opt/gitlab/.configured
  become: true
